from typing import Optional

import numpy as np
import cv2
import torch
from PIL import Image
from sixdrepnet import SixDRepNet
from sixdrepnet import utils
from math import sin, cos


def iclip(x: float, xmin: int, xmax: int)-> int:
    if x < xmin: x = xmin
    if x > xmax: x = xmax
    return int(x)


class SixDRepNetMulti(SixDRepNet):
    def __init__(self, gpu_id : int=0, dict_path: str=''):
        super().__init__(gpu_id, dict_path)


    def _predict(self, img):
        """
        Predicts the persons head pose and returning it in euler angles.

        Parameters
        ----------
        img : array
            Face crop to be predicted

        Returns
        -------
        pitch, yaw, roll
        """
        if isinstance(img, np.ndarray):
            try:
                img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
                img = Image.fromarray(img)
            except:
                pass
        img = self.transformations(img)

        img = torch.Tensor(img[None, :])

        if self.gpu != -1:
            img = img.cuda(self.gpu)

        pred = self.model(img)

        euler_rad = utils.compute_euler_angles_from_rotation_matrices(pred)# * 180 / np.pi
        # p = euler[:, 0].cpu().detach().numpy()
        # y = euler[:, 1].cpu().detach().numpy()
        # r = euler[:, 2].cpu().detach().numpy()
        # return p, y, r
        return euler_rad.cpu().detach().numpy()
    # end

    def predict_angles(self, frame, face_boxes):
        # frame: (h:240, w:320, c:3)
        h, w, c = frame.shape
        n_faces = len(face_boxes)
        euler_rad = np.zeros((n_faces, 3))
        td = np.zeros((n_faces, 2), dtype=float)
        for i in range(n_faces):
            tx, ty, bx, by, prob = face_boxes[i]

            face_frame = frame[iclip(ty, 0, h):iclip(by, 0, h), iclip(tx, 0, w):iclip(bx, 0, w)]

            euler_rad[i:i + 1] = self._predict(face_frame)
            td[i, 0] = (tx + bx) / 2
            td[i, 1] = (ty + by) / 2

        # euler = euler_rad * 180 / np.pi
        return euler_rad, td
    # end

    def predict(self, frame, face_boxes=[]):
        euler_rad, td = self.predict_angles(frame, face_boxes)

        euler = euler_rad * 180 / np.pi

        return euler[:, 0], euler[:, 1], euler[:, 2], td[:, 0], td[:, 1]
    # end

    # def predict_old(self, frame, face_boxes=[]):
    #     # frame: (h:240, w:320, c:3)
    #     h, w, c = frame.shape
    #     n_faces = len(face_boxes)
    #     euler_rad = np.zeros((n_faces, 3))
    #     td = np.zeros((n_faces, 2), dtype=float)
    #     for i in range(n_faces):
    #         tx, ty, bx, by, prob = face_boxes[i]
    #
    #         face_frame = frame[iclip(ty, 0, h):iclip(by, 0, h), iclip(tx,0, w):iclip(bx, 0, w)]
    #
    #         euler_rad[i:i+1] = self._predict(face_frame)
    #         td[i, 0] = (tx+bx)/2
    #         td[i, 1] = (ty+by)/2
    #
    #     euler = euler_rad * 180/np.pi
    #     #      pitch,      yaw,         roll,        tdx,      tdy
    #     return euler[:,0], euler[:, 1], euler[:, 2], td[:, 0], td[:, 1]

    def plot_angles(self, img: np.ndarray, euler_rad: np.ndarray, td: np.ndarray):
        euler = euler_rad*180/np.pi
        self.plot(img, euler[:,0], euler[:,1],euler[:,2], td[:,0], td[:,1])

    def plot(self, img: np.ndarray,
             pitch: np.ndarray, yaw: np.ndarray, roll: np.ndarray,
             tdx: Optional[np.ndarray]=None, tdy: Optional[np.ndarray]=None,
             size: int=30):
        """
        Prints the person's name and age.
        If the argument 'additional' is passed, then it is appended after the main info.

        WARNING: 'pitch, yaw, roll', SAME ORDER of the angles generated by 'predict()'
            The original implementation of 'draw_axes' use a DIFFERENT ORDER of the angles!!!!!

        Parameters
        ----------
        img : array
            Target image to be drawn on
        pitch: int
            pitch rotation
        yaw : int
            yaw rotation
        roll: int
            roll rotation
        tdx : int , optional
            shift on x axis
        tdy : int , optional
            shift on y axis

        Returns
        -------
        img : array
        """

        pitch = pitch * np.pi / 180
        yaw = -(yaw * np.pi / 180)
        roll = roll * np.pi / 180

        for i in range(yaw.shape[0]):
            pitch_i = float(pitch[i])
            yaw_i = float(yaw[i])
            roll_i = float(roll[i])

            if tdx is not None and tdy is not None:
                tdx_i = tdx[i]
                tdy_i = tdy[i]
            else:
                height, width = img.shape[:2]
                tdx_i = int(width / 2)
                tdy_i = int(height / 2)

            # X-Axis pointing to right. drawn in red
            x1 = size * (cos(yaw_i) * cos(roll_i)) + tdx_i
            y1 = size * (cos(pitch_i) * sin(roll_i) + cos(roll_i) * sin(pitch_i) * sin(yaw_i)) + tdy_i

            # Y-Axis | drawn in green
            #        v
            x2 = size * (-cos(yaw_i) * sin(roll_i)) + tdx_i
            y2 = size * (cos(pitch_i) * cos(roll_i) - sin(pitch_i) * sin(yaw_i) * sin(roll_i)) + tdy_i

            # Z-Axis (out of the screen) drawn in blue
            x3 = size * (sin(yaw_i)) + tdx_i
            y3 = size * (-cos(yaw_i) * sin(pitch_i)) + tdy_i

            cv2.line(img, (int(tdx_i), int(tdy_i)), (int(x1), int(y1)), (0, 0, 255), 4)
            cv2.line(img, (int(tdx_i), int(tdy_i)), (int(x2), int(y2)), (0, 255, 0), 4)
            cv2.line(img, (int(tdx_i), int(tdy_i)), (int(x3), int(y3)), (255, 0, 0), 4)
        # end
        return img
    # end
# end

