rem Rscript -e "install.packages(c('RBGL'),repos='http://cran.us.r-project.org', quiet=TRUE, verbose=FALSE)"
Rscript -e "install.packages(c('BiocManager'),repos='http://cran.us.r-project.org', quiet=TRUE, verbose=FALSE)"
Rscript -e "BiocManager::install('RBGL', force=TRUE)"

Rscript -e "install.packages(c('pcalg'),repos='http://cran.us.r-project.org', quiet=TRUE, verbose=FALSE)"
Rscript -e "install.packages(c('kpcalg'),repos='http://cran.us.r-project.org', quiet=TRUE, verbose=FALSE)"
Rscript -e "install.packages(c('bnlearn'),repos='http://cran.us.r-project.org', quiet=TRUE, verbose=FALSE)"
Rscript -e "install.packages(c('D2C'),repos='http://cran.us.r-project.org', quiet=TRUE, verbose=FALSE)"
Rscript -e "install.packages(c('SID'),repos='http://cran.us.r-project.org', quiet=TRUE, verbose=FALSE)"
rem Rscript -e "install.packages(c('CAM'),repos='http://cran.us.r-project.org', quiet=TRUE, verbose=FALSE)"
rem Rscript -e "install.packages(c('RCIT'),repos='http://cran.us.r-project.org', quiet=TRUE, verbose=FALSE)"
Rscript -e "library(devtools); install_github('cran/CAM'); install_github('cran/momentchi2'); install_github('Diviyan-Kalainathan/RCIT', quiet=TRUE, verbose=FALSE)"

rem Rscript -e "install.packages(c('V8'),repos='http://cran.us.r-project.org', quiet=TRUE, verbose=FALSE)"
rem Rscript -e "install.packages(c('sfsmisc'),repos='http://cran.us.r-project.org', quiet=TRUE, verbose=FALSE)"
rem Rscript -e "install.packages(c('clue'),repos='http://cran.us.r-project.org', quiet=TRUE, verbose=FALSE)"
rem Rscript -e "install.packages('https://cran.r-project.org/src/contrib/Archive/randomForest/randomForest_4.6-14.tar.gz', repos=NULL, type='source')"
rem Rscript -e "install.packages(c('lattice'),repos='http://cran.us.r-project.org', quiet=TRUE, verbose=FALSE)"
rem Rscript -e "install.packages(c('devtools'),repos='http://cran.us.r-project.org', quiet=TRUE, verbose=FALSE)"
rem Rscript -e "install.packages(c('MASS'),repos='http://cran.us.r-project.org', quiet=TRUE, verbose=FALSE)"
rem Rscript -e "install.packages('BiocManager')"
rem Rscript -e "BiocManager::install(c('igraph'))"
rem Rscript -e "install.packages('https://cran.r-project.org/src/contrib/Archive/fastICA/fastICA_1.2-2.tar.gz', repos=NULL, type='source')"
rem Rscript -e "BiocManager::install(c('SID', 'bnlearn', 'pcalg', 'kpcalg', 'glmnet', 'mboost'))"
rem Rscript -e "install.packages('https://cran.r-project.org/src/contrib/Archive/CAM/CAM_1.0.tar.gz', repos=NULL, type='source')"
rem Rscript -e "install.packages('https://cran.r-project.org/src/contrib/sparsebnUtils_0.0.8.tar.gz', repos=NULL, type='source')"
rem Rscript -e "BiocManager::install(c('ccdrAlgorithm', 'discretecdAlgorithm'))"
rem
rem Rscript -e "install.packages('devtools')"
rem Rscript -e "library(devtools); install_github('cran/CAM'); install_github('cran/momentchi2'); install_github('Diviyan-Kalainathan/RCIT', quiet=TRUE, verbose=FALSE)"
rem Rscript -e "install.packages('https://cran.r-project.org/src/contrib/Archive/sparsebn/sparsebn_0.1.2.tar.gz', repos=NULL, type='source')"
