from pathlib import Path
from typing import Optional

import numpy as np
from scipy.spatial.distance import cdist

from human.clipreid import ClipReID
from stdlib import jsonx
from stdlib import loggingx as logging
from stdlib.is_instance import is_instance
from stdlib.jsonx import JSONConfiguration
from .face_analyzer import FaceAnalyzer
from .pose_analyzer import PoseAnalyzer
from .pose_analyzer import PoseClassifier
from .utils import CAM_TRACK_NAME, EMBEDDING, LabMonitoring, METRIC_TYPES, sort_tracks


# ---------------------------------------------------------------------------
# ImageEmbedding
# ---------------------------------------------------------------------------
# Note: we suppose ALL IMAGES MUST HAVE A DIFFERENT NAME
#   there are cases where this is not true, however, this happens
# with images in 'random_crop' and 'face_recognition' (or 'face_recognition_fallback')
# Because 'face_recognition' (or 'face_recognition_fallback') are used not so often
# we can IGNORE the problems generated by this case
#

class ImageEmbedding(LabMonitoring):

    def __init__(
        self,
        CONFIG: JSONConfiguration,
        face_analyzer: Optional[FaceAnalyzer]=None,
        pose_analyzer: Optional[PoseAnalyzer]=None
    ):
        super().__init__(CONFIG, "image_embedding")

        assert isinstance(face_analyzer, Optional[FaceAnalyzer])
        assert isinstance(pose_analyzer, Optional[PoseAnalyzer])

        self.face_analyzer: Optional[FaceAnalyzer] = face_analyzer
        self.pose_analyzer: Optional[PoseAnalyzer] = pose_analyzer

        self.embedding_class = CONFIG.get("image_embedding.embedding_class", "clipreid.ClipReID")
        self.model_name = CONFIG.get("image_embedding.model_name", "DukeMTMC__cnn_base")
        self.metric = CONFIG.get("image_embedding.metric", "cosine")
        self.top_k = CONFIG.get("image_embedding.top_k", -1)
        self.images_folders = CONFIG.get("image_embedding.image_folders", ["random_crop"])
        self.valid_folders = CONFIG.get("image_embedding.valid_folders", ["random_crop"])

        self.pose_threshold = CONFIG.get("image_embedding.pose_threshold", 0.66)
        self.valid_poses = CONFIG.get("image_embedding.valid_poses", [])

        self.save_distances = CONFIG.get("image_embedding.save_distances", False)

        assert is_instance(face_analyzer, Optional[FaceAnalyzer])
        assert is_instance(pose_analyzer, Optional[PoseAnalyzer])

        assert is_instance(self.metric, METRIC_TYPES)
        # assert is_instance(self.linkage, Literal["average", "complete", "single", "ward"])
        assert self.embedding_class == "clipreid.ClipReID"

        self._image_embedding_map: dict[Path, EMBEDDING] = {}
        self._track_embeddings_map: dict[CAM_TRACK_NAME, list[EMBEDDING]] = {}

        self._track_selected_images: dict[CAM_TRACK_NAME, list[Path]] = {}
        self._track_selected_embeddings: dict[CAM_TRACK_NAME, list[EMBEDDING]] = {}

        self._track_root: Path = None

        self._log = logging.getLogger("ImageEmbedding")
        pass

    # -----------------------------------------------------------------------
    # Operations
    # -----------------------------------------------------------------------

    @property
    def image_embedding_map(self) -> dict[Path, EMBEDDING]:
        return self._image_embedding_map

    @property
    def track_embeddings_map(self) -> dict[CAM_TRACK_NAME, list[EMBEDDING]]:
        return self._track_selected_embeddings

    @property
    def track_images_map(self) -> dict[CAM_TRACK_NAME, list[Path]]:
        return self._track_selected_images

    # -----------------------------------------------------------------------
    # Operations
    # -----------------------------------------------------------------------

    def analyze(self, tracks_root: Path):
        assert is_instance(tracks_root, Path)

        self._update_parameters_using_external_analyzers()

        self._track_root = tracks_root

        self._log.info(f"Analyzing {tracks_root} ...")

        track_dirs = [
            track_dir
            for track_dir in tracks_root.iterdir()
            if self._is_valid_track(track_dir)
        ]
        track_dirs: list[Path] = sort_tracks(track_dirs)
        n = len(track_dirs)

        for i, track_dir in enumerate(track_dirs):
            self._log.infot(f"... {track_dir.name} ({i+1:4}/{n})")

            images_pose: dict[str, PoseClassifier] = self._load_images_pose(track_dir)
            selected_images: list[Path] = self._select_images(track_dir, images_pose)

            selected_embeddings: list[EMBEDDING] = [
                self.get_image_embedding(image_file)
                for image_file in selected_images
            ]

            track_name = track_dir.name
            self._track_selected_images[track_name] = selected_images
            self._track_selected_embeddings[track_name] = selected_embeddings

            self._save_images_distances(track_dir, selected_images, selected_embeddings)

            # self.get_track_images_embeddings(track_dir)
        # end
        self._cleanup()
        self._log.info(f"Done")
    # end

    def _update_parameters_using_external_analyzers(self):
        if self.face_analyzer is not None and self.face_analyzer.enabled:
            # add "face" folder to 'valid_folders'
            self.valid_folders += ["face"]

        if self.pose_analyzer is not None and self.pose_analyzer.enabled:
            # no update is necessary because it is used "pose.json" IF it is available
            pass

    def _is_valid_track(self, track_dir: Path) -> bool:

        if not track_dir.name.endswith("_DONE"):
            return False

        for valid_folder in self.valid_folders:
            if not (track_dir / valid_folder).exists():
                return False

        return True

    def get_image_embedding(self, image_path: Path) -> EMBEDDING:
        assert isinstance(image_path, Path)

        if image_path in self._image_embedding_map:
            return self._image_embedding_map[image_path]

        image_embedding: EMBEDDING = ClipReID.represent(image_path, self.model_name)
        self._image_embedding_map[image_path] = image_embedding

        return image_embedding

    def _load_images_pose(self, track_dir: Path) -> dict[str, PoseClassifier]:
        pose_file = track_dir / "pose.json"

        images_pose: dict[str, dict] = {}
        if pose_file.exists():
            images_pose = jsonx.load(pose_file)

        # convert dict in 'PoseClassifier'
        return {
            image_name: PoseClassifier(images_pose[image_name], self.pose_threshold)
            for image_name in images_pose
        }
    # end

    def _select_images(self, track_dir: Path, images_pose: dict[str, PoseClassifier]) -> list[Path]:
        images_list: list[Path] = []
        for images_folder in self.images_folders:
            images_dir = track_dir / images_folder
            if not images_dir.exists(): continue

            for image_file in images_dir.iterdir():
                if self._is_valid_image(image_file, images_pose):
                    images_list.append(image_file)
            # end
        # end
        return images_list
    # end

    def _is_valid_image(self, image_file: Path, images_pose: dict[str, PoseClassifier]) -> bool:
        # is is not an image
        if not image_file.name.endswith(".jpg"):
            return False

        # there are no registered images in images_pose dictionary
        if len(images_pose) == 0:
            return True

        # the image is not registered in images_pose dictionary
        if image_file.name not in images_pose:
            return False

        pose_classifier: PoseClassifier = images_pose[image_file.name]

        # there is not a valid pose (no keypoints OR all keypoints are below
        # the threshold)
        if not pose_classifier.is_valid():
            return False

        # all poses are valid
        if len(self.valid_poses) == 0:
            return True

        # it is nota valid pose
        which_pose = pose_classifier.which_pose()
        if not which_pose in self.valid_poses:
            return False

        return True
    # end

    def get_track_selected_images(self, track_dir: Path) -> list[Path]:
        return self._track_selected_images.get(track_dir.name, [])

    def get_track_single_embedding(self, track_dir: Path) -> Optional[EMBEDDING]:
        #
        # THIS returns ONLY THE FIRST embedding of the track
        #   it is supposed top_k == -1
        #
        assert is_instance(track_dir, Path)
        assert self.top_k == -1, f"Track embedding for top_k={self.top_k} not supported"

        track_embeddings = self.get_track_embeddings(track_dir)

        return track_embeddings[0] if len(track_embeddings) > 0 else None
    # end

    def get_track_embeddings(self, track_dir: Path) -> list[EMBEDDING]:
        #
        # THIS returns the EMBEDDINGS of the track
        #
        assert is_instance(track_dir, Path)

        images_embedding: list[EMBEDDING] = self.get_track_images_embeddings(track_dir)

        # if top_k=-1 to compute the mean of the embeddings of all selected images in the track
        if self.top_k == -1 and len(images_embedding) > 1:
            images_embedding = [np.array(images_embedding).mean(axis=0).reshape(-1)]

        self._track_embeddings_map[track_dir.name] = images_embedding

        return images_embedding
    # end

    def get_track_images_embeddings(self, track_dir: Path) -> list[EMBEDDING]:
        #
        # THIS returns the EMBEDDING of the IMAGES USED to compute the EMBEDDING of the track
        #
        assert is_instance(track_dir, Path)

        track_name = track_dir.name

        return [] if not track_name in self._track_selected_embeddings else  self._track_selected_embeddings[track_name]

        # if track_name in self._track_embeddings_map:
        #     return self._track_embeddings_map[track_name]
        #
        # images_list = [] if track_name not in self._track_selected_images \
        #     else self._track_selected_images[track_name]
        #
        # images_embedding: list[EMBEDDING] = [
        #     self.get_image_embedding(image_file)
        #     for image_file in images_list
        # ]

        # self._save_images_distances(track_dir, images_list, images_embedding)

        # return images_embedding
    # end

    def _save_images_distances(self, track_dir: Path, image_files: list[Path], image_embeddings: list[EMBEDDING]):
        if not self.save_distances or len(image_files) == 0:
            return

        # image names
        image_names = [
            image_path.name
            for image_path in image_files
        ]
        n = len(image_files)

        # mean_embedding
        mean_embedding: EMBEDDING = np.mean(image_embeddings, axis=0)

        matrix_distances = cdist(image_embeddings, image_embeddings, metric=self.metric)
        center_distances = cdist([mean_embedding], image_embeddings, metric=self.metric).reshape(-1)
        image_distances = center_distances.tolist()

        pair_distances = [0.]
        for i in range(1, n):
            pair_distances.append(float(matrix_distances[i-1,i]))

        data = {
            "metric": self.metric,
            "images": image_names,
            "pair_distances": pair_distances,
            "matrix_distances": matrix_distances,
            "matrix_mean": float(matrix_distances.mean()),
            "matrix_sdev": float(matrix_distances.std()),
            "distances": {
                image_names[i]: image_distances[i]
                for i in range(n)
            },
            "mean": float(center_distances.mean()),
            "sdev": float(center_distances.std())
        }

        jsonx.dump(data, track_dir / "random_crop/distances.json")
    # end

    def filter_same_images(self, image_paths: list[Path], max_similarity: float) -> list[Path]:
        n = len(image_paths)
        min_distance = 1-max_similarity
        embeddings: list[EMBEDDING] = [
            self.get_image_embedding(image_path)
            for image_path in image_paths
        ]
        dist_matrix = self.embeddings_distances(embeddings, embeddings)
        excluded = set()
        for i in range(n):
            for j in range(i+1, n):
                if dist_matrix[i,j] <= min_distance:
                    excluded.add(j)

        return [
            image_paths[i]
            for i in range(n)
            if i not in excluded
        ]
    # end

    def embeddings_distances(self, embeddings_i: list[EMBEDDING], embeddings_j: list[EMBEDDING]) -> np.ndarray:
        assert is_instance(embeddings_i, list[EMBEDDING])
        assert is_instance(embeddings_j, list[EMBEDDING])

        if len(embeddings_i) == 0 or len(embeddings_j) == 0:
            return np.zeros((len(embeddings_i), len(embeddings_j)), dtype=float)
        if np.isnan(embeddings_i).any() or np.isnan(embeddings_j).any():
            return np.zeros((len(embeddings_i), len(embeddings_j)), dtype=float)

        try:
            dist_matrix: np.ndarray = cdist(embeddings_i, embeddings_j, metric=self.metric)
        except Exception as e:
            self._log.exception(e)
            dist_matrix = np.zeros((len(embeddings_i), len(embeddings_j)), dtype=float)
        return dist_matrix
    # end

    def pair_similarity(self, embeddings_i: list[EMBEDDING], embeddings_j: list[EMBEDDING]) -> float:
        # WARNING: similarity is in range [0,1]
        #   WITH 1 THE BEST  SIMILARITY
        #   WITH 0 THE WORST SIMILARITY
        assert is_instance(embeddings_i, list[EMBEDDING])
        assert is_instance(embeddings_j, list[EMBEDDING])

        if len(embeddings_i) == 0 or len(embeddings_j) == 0:
            return 0.
        if np.isnan(embeddings_i).any() or np.isnan(embeddings_j).any():
            return 0.

        dist_matrix = self.embeddings_distances(embeddings_i, embeddings_j)
        if np.isnan(dist_matrix).any():
            return 0.

        similarity_matrix = 1 - dist_matrix

        # top_k == 1        max similarity (min distance)
        # top_k  > 1        mean of the top k max similarities
        # top_k == 0        mean of all similarities
        # top_k == -1       similarity between mean of the embeddings

        if self.top_k == 1:
            pair_similarity = similarity_matrix.max()
        elif self.top_k == 0:
            pair_similarity = similarity_matrix.mean()
        elif self.top_k > 1:
            similarity_vector = similarity_matrix.reshape(-1)
            # sorted ascending
            similarity_vector.sort()
            k = min(self.top_k, len(similarity_vector))
            pair_similarity = similarity_vector[-k:].mean()
        elif self.top_k == -1:
            # Note: ALREADY prepared
            # mean_embeddings_i = np.array(embeddings_i).mean(axis=0).reshape((1, -1))
            # mean_embeddings_j = np.array(embeddings_j).mean(axis=0).reshape((1, -1))
            # dist_matrix = cdist(mean_embeddings_i, mean_embeddings_j, metric='cosine')
            # pair_similarity = (1 - dist_matrix).max()
            pair_similarity = similarity_matrix.max()
        else:
            raise ValueError(f"Unsupported top_k {self.top_k}")

        return pair_similarity
    # end

    def _cleanup(self):
        ClipReID.dispose()
# end

# ---------------------------------------------------------------------------
# End
# ---------------------------------------------------------------------------
