from datetime import datetime
from datetimex import relativedifference, relativeperiods, clip_date

today = datetime.now()
print("-- hour --")
print(clip_date(today, freq='s'))
print(clip_date(today, freq='m'))
print(clip_date(today, freq='H'))

print("-- day --")
print(clip_date(today, freq='D'))
print(clip_date(today, freq='DS'))
print(clip_date(today, freq='DE'))

print("-- month --")
print(clip_date(today, freq='M'))
print(clip_date(today, freq='MS'))
print(clip_date(today, freq='ME'))

print("-- week --")
print(clip_date(today, freq='W'))
print(clip_date(today, freq='W-MON'))
print(clip_date(today, freq='W-TUE'))
print(clip_date(today, freq='W-WED'))
print(clip_date(today, freq='W-THU'))
print(clip_date(today, freq='W-FRI'))
print(clip_date(today, freq='W-SAT'))
print(clip_date(today, freq='W-SUN'))

print("-- year/start --")
print(clip_date(today, freq='Y'))
print(clip_date(today, freq='Y-JAN'))
print(clip_date(today, freq='Y-FEB'))
print(clip_date(today, freq='Y-MAR'))
print(clip_date(today, freq='Y-APR'))
print(clip_date(today, freq='Y-MAY'))
print(clip_date(today, freq='Y-JUN'))
print(clip_date(today, freq='Y-JUL'))
print(clip_date(today, freq='Y-AUG'))
print(clip_date(today, freq='Y-SEP'))
print(clip_date(today, freq='Y-OCT'))
print(clip_date(today, freq='Y-NOV'))
print(clip_date(today, freq='Y-DEC'))

print("-- year/end --")
print(clip_date(today, freq='YE'))
print(clip_date(today, freq='YE-JAN'))
print(clip_date(today, freq='YE-FEB'))
print(clip_date(today, freq='YE-MAR'))
print(clip_date(today, freq='YE-APR'))
print(clip_date(today, freq='YE-MAY'))
print(clip_date(today, freq='YE-JUN'))
print(clip_date(today, freq='YE-JUL'))
print(clip_date(today, freq='YE-AUG'))
print(clip_date(today, freq='YE-SEP'))
print(clip_date(today, freq='YE-OCT'))
print(clip_date(today, freq='YE-NOV'))
print(clip_date(today, freq='YE-DEC'))
