
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "classinterfaceABSTRACT CLASS ENUM EXTENDS FINAL IMPLEMENTS INTERFACE NAME PRIVATE PROTECTED PUBLIC STATIC\n    type : NAME tparams arrays\n    \n    typelist    : type ',' typelist\n                | type\n                |\n    \n    tparams : '<' tparamlist '>'\n            |\n    \n    tparamlist  : type ',' tparamlist\n                | type\n    \n    arrays  : '[' ']' arrays\n            |\n    \n    method : type NAME '(' paramlist ')'\n    \n    paramlist   : param ',' paramlist\n                | param\n                |\n    \n    param   : type NAME\n    \n    modifier    : PUBLIC\n                | PROTECTED\n                | PRIVATE\n                | STATIC\n                | FINAL\n                | ABSTRACT\n    \n    classinterface  :   modifier classinterface\n                    |   CLASS     type extimpl\n                    |   INTERFACE type extimpl\n                    |   ENUM      type extimpl\n    \n    extimpl : EXTENDS    typelist IMPLEMENTS typelist\n            | IMPLEMENTS typelist EXTENDS    typelist\n            | EXTENDS    typelist\n            | IMPLEMENTS typelist\n            |\n    "
    
_lr_action_items = {'CLASS':([0,2,6,7,8,9,10,11,],[3,3,-16,-17,-18,-19,-20,-21,]),'INTERFACE':([0,2,6,7,8,9,10,11,],[4,4,-16,-17,-18,-19,-20,-21,]),'ENUM':([0,2,6,7,8,9,10,11,],[5,5,-16,-17,-18,-19,-20,-21,]),'PUBLIC':([0,2,6,7,8,9,10,11,],[6,6,-16,-17,-18,-19,-20,-21,]),'PROTECTED':([0,2,6,7,8,9,10,11,],[7,7,-16,-17,-18,-19,-20,-21,]),'PRIVATE':([0,2,6,7,8,9,10,11,],[8,8,-16,-17,-18,-19,-20,-21,]),'STATIC':([0,2,6,7,8,9,10,11,],[9,9,-16,-17,-18,-19,-20,-21,]),'FINAL':([0,2,6,7,8,9,10,11,],[10,10,-16,-17,-18,-19,-20,-21,]),'ABSTRACT':([0,2,6,7,8,9,10,11,],[11,11,-16,-17,-18,-19,-20,-21,]),'$end':([1,12,13,14,15,16,17,18,19,20,22,23,24,25,26,27,31,32,33,34,35,37,38,39,40,],[0,-22,-30,-6,-30,-30,-23,-4,-4,-10,-24,-25,-28,-3,-29,-1,-4,-4,-4,-10,-5,-26,-2,-27,-9,]),'NAME':([3,4,5,18,19,21,31,32,33,36,],[14,14,14,14,14,14,14,14,14,14,]),'EXTENDS':([13,14,15,16,19,20,25,26,27,32,34,35,38,40,],[18,-6,18,18,-4,-10,-3,33,-1,-4,-10,-5,-2,-9,]),'IMPLEMENTS':([13,14,15,16,18,20,24,25,27,32,34,35,38,40,],[19,-6,19,19,-4,-10,31,-3,-1,-4,-10,-5,-2,-9,]),'<':([14,],[21,]),'[':([14,20,34,35,],[-6,28,28,-5,]),',':([14,20,25,27,30,34,35,40,],[-6,-10,32,-1,36,-10,-5,-9,]),'>':([14,20,27,29,30,34,35,40,41,],[-6,-10,-1,35,-8,-10,-5,-9,-7,]),']':([28,],[34,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'classinterface':([0,2,],[1,12,]),'modifier':([0,2,],[2,2,]),'type':([3,4,5,18,19,21,31,32,33,36,],[13,15,16,25,25,30,25,25,25,30,]),'extimpl':([13,15,16,],[17,22,23,]),'tparams':([14,],[20,]),'typelist':([18,19,31,32,33,],[24,26,37,38,39,]),'arrays':([20,34,],[27,40,]),'tparamlist':([21,36,],[29,41,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> classinterface","S'",1,None,None,None),
  ('type -> NAME tparams arrays','type',3,'p_type','javasig.py',68),
  ('typelist -> type , typelist','typelist',3,'p_typelist','javasig.py',75),
  ('typelist -> type','typelist',1,'p_typelist','javasig.py',76),
  ('typelist -> <empty>','typelist',0,'p_typelist','javasig.py',77),
  ('tparams -> < tparamlist >','tparams',3,'p_tparams','javasig.py',89),
  ('tparams -> <empty>','tparams',0,'p_tparams','javasig.py',90),
  ('tparamlist -> type , tparamlist','tparamlist',3,'p_tparamlist','javasig.py',97),
  ('tparamlist -> type','tparamlist',1,'p_tparamlist','javasig.py',98),
  ('arrays -> [ ] arrays','arrays',3,'p_arrays','javasig.py',105),
  ('arrays -> <empty>','arrays',0,'p_arrays','javasig.py',106),
  ('method -> type NAME ( paramlist )','method',5,'p_method','javasig.py',121),
  ('paramlist -> param , paramlist','paramlist',3,'p_paramlist','javasig.py',128),
  ('paramlist -> param','paramlist',1,'p_paramlist','javasig.py',129),
  ('paramlist -> <empty>','paramlist',0,'p_paramlist','javasig.py',130),
  ('param -> type NAME','param',2,'p_param','javasig.py',142),
  ('modifier -> PUBLIC','modifier',1,'p_modifier','javasig.py',153),
  ('modifier -> PROTECTED','modifier',1,'p_modifier','javasig.py',154),
  ('modifier -> PRIVATE','modifier',1,'p_modifier','javasig.py',155),
  ('modifier -> STATIC','modifier',1,'p_modifier','javasig.py',156),
  ('modifier -> FINAL','modifier',1,'p_modifier','javasig.py',157),
  ('modifier -> ABSTRACT','modifier',1,'p_modifier','javasig.py',158),
  ('classinterface -> modifier classinterface','classinterface',2,'p_classinterface','javasig.py',165),
  ('classinterface -> CLASS type extimpl','classinterface',3,'p_classinterface','javasig.py',166),
  ('classinterface -> INTERFACE type extimpl','classinterface',3,'p_classinterface','javasig.py',167),
  ('classinterface -> ENUM type extimpl','classinterface',3,'p_classinterface','javasig.py',168),
  ('extimpl -> EXTENDS typelist IMPLEMENTS typelist','extimpl',4,'p_extimpl','javasig.py',178),
  ('extimpl -> IMPLEMENTS typelist EXTENDS typelist','extimpl',4,'p_extimpl','javasig.py',179),
  ('extimpl -> EXTENDS typelist','extimpl',2,'p_extimpl','javasig.py',180),
  ('extimpl -> IMPLEMENTS typelist','extimpl',2,'p_extimpl','javasig.py',181),
  ('extimpl -> <empty>','extimpl',0,'p_extimpl','javasig.py',182),
]
