import pandas as pd
import numpy as np


##***AutoRegHelper - start***************

# process number of weeks lag for a (set of) features
def number_of_weeks_lag(weeks, df, dowCol, features):
        for fet in features:
            for i in range(int(weeks)):
                week = i+1
                df[fet+'_w'+str(week)] = df.groupby([dowCol])[fet].shift(week)
        return df

# process number of days lag for a set of features    
def number_of_days_lag(days, df, features):
        for fet in features:
            for i in range(int(days)):
                day = i+1
                df[fet+'_d'+str(day)] = df[fet].shift(day)
        return df

# remove columns wiht null for all introduced weeks lag columns for a set of features
def remove_null_weeks_lag(weeks, df, features):
        for fet in features:
            for i in range(int(weeks)):
                week = i+1
                df = df[df[fet+'_w'+str(week)].notnull()]
        return df

 # remove columns wiht null for all introduced day lag columns for a set of features
def remove_null_days_lag(days, df, features):
        for fet in features:
            for i in range(int(days)):
                day = i+1
                df = df[df[fet+'_d'+str(day)].notnull()]
        return df


def expand_autoregressive_features(targetWeekLag, targetDayLag, inputsWeekLag, inputsDayLag, df, dowCol, targetFeature, inputFeaturesForAutoRegression):    
        # expand week lag and day lag for target feature and set of input features
        df = number_of_weeks_lag(targetWeekLag, df, dowCol, [targetFeature])
        df = number_of_days_lag(targetDayLag, df, [targetFeature])    
        df = number_of_weeks_lag(inputsWeekLag, df, dowCol, inputFeaturesForAutoRegression)
        df = number_of_days_lag(inputsDayLag, df, inputFeaturesForAutoRegression)    
        return df

# Remove all null values
def remove_null_values(targetWeekLag, targetDayLag, inputsWeekLag, inputsDayLag, df, targetFeature, inputFeaturesForAutoRegression):
        # remove columns with null values generated by week lag and day lag for target feature and set of input features
        df = remove_null_weeks_lag(targetWeekLag, df, [targetFeature])
        df = remove_null_days_lag(targetDayLag, df, [targetFeature])
        df = remove_null_weeks_lag(inputsWeekLag, df, inputFeaturesForAutoRegression)
        df = remove_null_days_lag(inputsDayLag, df, inputFeaturesForAutoRegression)
        return df

#****** AutoRegHelper - End ******************


